app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.home, name='homepage'),
    path('error', views.home, name='error'),
    path('settings', views.settings, name='settings'),
    path('download', views.download, name='download')
]

django_content_downloader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django.forms import ModelForm
from django import forms
from pytube import YouTube
from pytube import exceptions

import re


class YouTubeURLForm(forms.Form):
    youtube_url = forms.URLField(label=False,
                                 widget=forms.TextInput(
                                     attrs={'placeholder': 'Paste youtube url.', 'name': 'search'}),
                                 max_length=47)

    def clean_youtube_url(self):
        data = self.cleaned_data['youtube_url']
        try:
            video = YouTube(data).streams
        except exceptions.PytubeError as err:
            raise forms.ValidationError(err, code='invalid_url')

        return data

    @staticmethod
    def validate_link(url):
        # 1st check if url is youtube url
        youtube_regex = (
            r'(https?://)?(www\.)?'
            '(youtube|youtu|youtube-nocookie)\.(com|be)/'
            '(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})')

        youtube_regex_match = re.match(youtube_regex, url)

        if youtube_regex_match:
            return youtube_regex_match

        return youtube_regex_match


class YouTubeDownloadForm(forms.Form):
    class Meta:
        fields = []

    select_format = forms.ChoiceField(widget=forms.Select, choices=[('Video', 'Video'), ('Audio', 'Audio')])
    select_resolution = forms.ChoiceField(widget=forms.Select)
    select_metadata = forms.BooleanField(widget=forms.CheckboxInput, required=False)

    def __init__(self, res_list, *args, **kwargs):
        super(YouTubeDownloadForm, self).__init__(*args, **kwargs)
        self.fields['select_resolution'] = forms.ChoiceField(choices=res_list)

    def clean_select_format(self):
        data = self.cleaned_data['select_format']
        allowed_formats = ['Audio', 'Video']
        if data not in allowed_formats:
            raise forms.ValidationError("invalid format", code='invalid_format')

        return data

    def clean_select_resolution(self):
        data = self.cleaned_data['select_resolution']
        #  [('1080p', '1080p'), ('440p', '440p'), ('144p', '144p'), ('2160p', '2160p'),
        #                       ('240p', '240p'),
        #                       ('360p', '360p'), ('480p', '480p'), ('720p', '720p')]
        allowed_resolution = ['1080p', '440p', '144p', '2160p', '240p', '360p', '480p', '720p']

        if data not in allowed_resolution:
            raise forms.ValidationError("invalid resolution", code='invalid_resolution')

app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django_content_downloader.settings import BASE_DIR
from .forms import YouTubeURLForm
from .forms import YouTubeDownloadForm

import mimetypes
import os
import pytube.metadata
from pathlib import Path
from os.path import basename
from pytube import *
from zipfile import ZipFile

import ffmpeg
import subprocess

video_url = ''


def home(request):
    form = YouTubeURLForm
    context = {'form': form}
    return render(request, 'index.html', context)


def settings(request):
    global video_url


    if request.method == 'POST':
        form = YouTubeURLForm(request.POST)
        if form.is_valid():

            video_url = form.cleaned_data['youtube_url']
            video = YouTube(video_url)

            stream = video.streams
            resolution_list = []
            control_set = set()
            x = 1

            for i in stream:  # get list with all resolutions possible
                if i.resolution is not None:
                    if i.resolution not in control_set:
                        y = (i.resolution, i.resolution)
                        resolution_list.append(y)
                        x = x + 1
                        control_set.add(i.resolution)
            resolution_list.sort(key=lambda x: x[1])    # sorting by second element of nested tuple

            form_download = YouTubeDownloadForm(resolution_list)
            context = {'form': form_download, 'resolution_list': resolution_list, 'url': video_url}
            return render(request, 'download.html', context)

    else:
        form = YouTubeURLForm()

    context = {'form': form}

    return render(request, 'error.html', context, status=422)


def download(request, url=video_url):
    if request.method == 'POST':
        global video_url
        if video_url is None or video_url == '':
            video_url = url

        filespath = os.path.dirname(os.path.abspath(__file__))
        filespath = os.path.join(BASE_DIR, "/app/files/")

        filename = "downloaded"

        file_format = request.POST['select_format']
        metadata_status = request.POST.get('select_metadata', 'off')
        vid = YouTube(video_url)

        # section for downloading the file
        if file_format == "Video":
            ext = ".mp4"
            filename = "filename" + ".mp4"
            resolution = request.POST['select_resolution']
            vid.streams.filter(res=resolution).first().download(output_path=filespath, filename=filename)

        elif file_format == "Audio":
            ext = ".mp3"
            filename = "filename" + ".mp3"
            vid.streams.filter(only_audio=True).first().download(output_path=filespath, filename=filename)

        if metadata_status == 'on':
            metadata = {"title": vid.title, "author": vid.author, "description": vid.description,
                        "publish_date": str(vid.publish_date), "keywords": vid.keywords, "length": vid.length,
                        "views": vid.views}
            # Writing to file
            meta_name = 'metadata.json'
            with open(filespath + meta_name, "w") as file1:
                # Writing data to a file
                file1.write(str(metadata))

            zip_name = 'content.zip'
            zipObj = ZipFile(filespath + zip_name, 'w')

            # Add multiple files to the zip
            zipObj.write(filespath + meta_name, basename(filespath + meta_name))
            zipObj.write(filespath + filename, basename(filespath + filename))
            zipObj.close()

            # Open the file for reading content
            path = open(filespath + 'content.zip', 'rb')
            # Set the return value of the HttpResponse
            response = HttpResponse(path, content_type='application/x-zip-compressed')

            # Set the HTTP header for sending to browser
            response['Content-Disposition'] = "attachment; filename=%s" % zip_name

            path.close()
            os.remove(filespath + meta_name)
            os.remove(filespath + zip_name)
            os.remove(filespath + filename)

            return response
        else:
            path = open(filespath + filename, 'rb')
            # Set the return value of the HttpResponse
            if file_format == "Video":
                response = HttpResponse(path, content_type="video/mp4")
            elif file_format == "Audio":
                response = HttpResponse(path, content_type="audio/mpeg")
            # Set the HTTP header for sending to browser
            response['Content-Disposition'] = "attachment; filename=%s" % (vid.title + ext)
            path.close()
            os.remove(filespath + filename)
            return response

    else:
        form = YouTubeDownloadForm()

    context = {'form': form}

    return render(request, 'index.html', context, status=422)

app/templates/download.html
{% extends 'index.html' %}
{% load static %}

{% block title %} Download the video {% endblock %}
{% block header %} DOWNLOAD SETTINGS {% endblock %}

{% block content %}
<div class="wrapper">
    <div class="title">
    </div>
    <form class="form" id="id_download_form" action="download" method="POST">
       {% csrf_token %}
        <div class="inputfield">
            <label>FORMAT</label>
            <div class="custom_select">
              {{ form.select_format }}
            </div>
         </div> 
        <div class="inputfield">
          <label>RESOLUTION</label>
          <div class="custom_select">
            {{ form.select_resolution }}
          </div>
       </div> 
      <div class="metadata">
        <label>METADATA </label>
        <label class="switch">
            {{ form.select_metadata }}
            <span class="slider round"></span>
          </label>
       </div>
        <button class="button" id="id_download_button" type="submit">
        <div class="content">
          <i class="fa-regular fa-circle-down"></i>
          <span class="button-text">DOWNLOAD</span>
        </div>
      </button>

    </form>
    </div>
</div>


<script>
    document.querySelector('#id_select_format').onchange = ev => {
      const value = ev.target.value;
      if (value === 'Audio') {
        document.querySelector('#id_select_resolution').disabled = true;
      } else {
        document.querySelector('#id_select_resolution').disabled = false;
      }
    }

  let button = document.querySelector(".button");

  button.addEventListener("click", ()=>{
    button.classList.add("active");

    setTimeout(()=>{
      button.classList.remove("active");
      document.querySelector("i").classList.replace("fa-circle-down", "fa-circle-check")
      document.querySelector(".button-text").innerText = "DOWNLOADED";
    },6000)
  })

</script>
{% endblock %}

app/templates/error.html
{% extends 'index.html' %}
{% load static %}

{% block title %} Error {% endblock %}
{% block header %}DOWNLOAD YOUTUBE VIDEO {% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>

{% block content %}
      <div class="invalid_url show">
      <span class="fa-solid fa-circle-exclamation"></span>
         <span class="msg"> {{ form.errors.youtube_url }}</span>
      </div>
    <div class="container">
        <div class="URL-add-container">
            <form class="search-section" action="settings" method="POST">
                {% csrf_token %}
                {{ form.youtube_url }}
                <button type="submit">PROCEED</button>
            </form>
        </div>

      <script>
       $('button').click(function(){
         if (1==1){
               $('.invalid_url').addClass("show");
               $('.invalid_url').removeClass("hide");
               $('.invalid_url').addClass("showAlert");
          }
        });

        $('.close').click(function(){
          $('.invalid_url').removeClass("show");
          $('.invalid_url').addClass("hide");
        });
      </script>
{% endblock %}

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static "css/style2.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/70bd267ff8.js" crossorigin="anonymous"></script>
    <title>{% block title %} Home {% endblock %}</title>
    <h1> {% block header %}DOWNLOAD YOUTUBE VIDEO{% endblock %} </h1>
</head>

<body>
{% block content %}

    <div class="container">
        <div class="URL-add-container">
            <form class="search-section" action="settings" method="POST">
                {% csrf_token %}
                {{ form.youtube_url }}
                <button type="submit" id="id_button_submit">PROCEED</button>
            </form>
        </div>

    </div>
{% endblock %}
    <div class="bottom-content">
        <b>lossless compression</b>
    </div>
</body>